package ran.front;

import javafx.fxml.FXML;

import javafx.scene.text.Text;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

public class AdminUIController {
	@FXML
	private Text header;
	@FXML
	private Button click;
	@FXML
	private Button click1;
	@FXML
	Button click2;

	// Event Listener on Button[#click].onAction
	@FXML
	public void jump(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Button[#click1].onAction
	@FXML
	public void jumppp(ActionEvent event) {
		// TODO Autogenerated
	}

	@FXML
	public void addDoctor(ActionEvent event) {
	}
}
