package hospital.ui.view.appointment;

import javafx.fxml.FXML;
import hospital.model.Patient;
import javafx.beans.property.SimpleStringProperty;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

public class AppointmentOverviewController {

	private ObservableList<Patient> patientList = FXCollections.observableArrayList();
	@FXML
	private TableView<Patient> appointmentTable;
	@FXML
	private TableColumn<Patient, SimpleStringProperty> appointIDTableColumn;
	@FXML
	private TableColumn<Patient, SimpleStringProperty> patientIDTableColumn;
	@FXML
	private TableColumn<Patient, SimpleStringProperty> doctorIDTableColumn;
	@FXML
	private TableColumn<Patient, SimpleStringProperty> dateTableColumn;
	@FXML
	private Label appointIDLbl;
	@FXML
	private Label patientIDLbl;
	@FXML
	private Label dateLbl;
	@FXML
	private Label doctorIDLbl;

	// Event Listener on Button.onAction
	@FXML
	public void handleEdit(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void handleDelete(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void handleAdd(ActionEvent event) {
		// TODO Autogenerated
	}
}
